spring.application.name=car-dealership

spring.datasource.url=jdbc:mysql://localhost:3306/car-dealership
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


server.port=8080

